#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 22 09:12:09 KST 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim cnn_tb_behav -key {Behavioral:sim_1:Functional:cnn_tb} -tclbatch cnn_tb.tcl -view /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sim_1/imports/project_Guess_Number/cnn_tb_behav.wcfg -log simulate.log"
xsim cnn_tb_behav -key {Behavioral:sim_1:Functional:cnn_tb} -tclbatch cnn_tb.tcl -view /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sim_1/imports/project_Guess_Number/cnn_tb_behav.wcfg -log simulate.log

