# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.runs/synth_1/OV_VGA.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.cache/wt [current_project]
set_property parent.project_path /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/jsh-laptop/.Xilinx/Vivado/2024.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w4.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_conv1_b.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w2.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w5.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w9.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w7.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w3.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_b.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w0.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w1.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_conv1_w.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w6.mem
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/Downloads/FINAL_fc_w8.mem
}
read_verilog -library xil_defaultlib -sv {
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/OV7670_2.srcs/sources_1/imports/new/Image_conv.sv
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/OV7670_2.srcs/sources_1/imports/new/OV_MASTER.sv
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/OV7670_2.srcs/sources_1/imports/new/OV_read.sv
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/OV7670_2.srcs/sources_1/imports/new/VGA_controller.sv
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/new/cnn_top.sv
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/OV7670_2.srcs/sources_1/imports/new/make_sio_c.sv
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/OV7670_2.srcs/sources_1/imports/new/ov7670_.sv
  /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/imports/OV7670_2.srcs/sources_1/imports/new/VGA.sv
}
read_ip -quiet /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/constrs_1/imports/fpga/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/constrs_1/imports/fpga/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/jsh-laptop/workspace_ondevice_2/fpga/self_study/project_Guess_Number/project_Guess_Number.srcs/utils_1/imports/synth_1/OV_VGA.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top OV_VGA -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef OV_VGA.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file OV_VGA_utilization_synth.rpt -pb OV_VGA_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
